#input_path: "data/sample.txt"
# input_path: "data/TinyStoriesV2-GPT4-train-10k.txt"
# vocab_size: 1000
vocab_path: "checkpoints/tinystories10k_vocab.json"
merges_path: "checkpoints/tinystories10k_merges.txt"
input_path: "data/TinyStoriesV2-GPT4-train.txt"
vocab_size: 10000
# vocab_path: "checkpoints/tinystories_vocab.json"
# merges_path: "checkpoints/tinystories_merges.txt"
#input_path: "data/TinyStoriesV2-GPT4-valid.txt"
# input_path: "data/owt_train.txt"
# vocab_size: 32000
# vocab_path: "checkpoints/owt_vocab.json"
# merges_path: "checkpoints/owt_merges.txt"
special_tokens: ["<|endoftext|>"] #, "<|unknown|>"]
split_token: "<|endoftext|>"
num_chunks: 2
pretokenization_pattern: r"""'(?:[sdmt]|ll|ve|re)| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+"""